"use client";
import { useEffect, useMemo, useState } from "react";

type Period={enabled:boolean;start:string;lastOrder:string;end:string;days:number[]};
type Hours={lunchEnabled:boolean;lunchStart:string;lunchLastOrder:string;lunchEnd:string;lunchDays:number[];dinnerEnabled:boolean;dinnerStart:string;dinnerLastOrder:string;dinnerEnd:string;dinnerDays:number[]};
type Exception={date:string;status:"DEFAULT"|"CLOSED"|"CUSTOM"|"EVENT"|"CONTINUOUS";lunchEnabled:boolean;dinnerEnabled:boolean;lunchStart:string;lunchEnd:string;dinnerStart:string;dinnerEnd:string;continuousStart:string;continuousEnd:string;continuousLastOrder:string;note:string};
type CategoryAvailability={category:string;enabled:boolean;startTime:string;endTime:string;days:number[];note:string};
const labels=[[1,"月"],[2,"火"],[3,"水"],[4,"木"],[5,"金"],[6,"土"],[7,"日"]] as const;
const categoryLabels:Record<string,string>={"food-tsukemen":"つけ麺","food-udon":"うどん・ほうとう","food-pasta":"パスタ","food-don":"ご飯もの","food-side":"サイド","dessert":"デザート","soft-cafe":"カフェ","soft-simple":"ソフトドリンク","soft-mocktail":"モクテル","alcohol-main":"ビール・焼酎など","alcohol-cocktail":"カクテル"};

export default function BusinessHoursManager(){
  const[hours,setHours]=useState<Hours|null>(null),[exceptions,setExceptions]=useState<Exception[]>([]),[message,setMessage]=useState("読み込んでいます…"),[saving,setSaving]=useState(false),[month,setMonth]=useState(()=>new Date().toISOString().slice(0,7)),[date,setDate]=useState("");
  useEffect(()=>{fetch("/api/v1/kitchen/business-hours",{cache:"no-store"}).then(async response=>{if(!response.ok)throw new Error();return response.json()}).then(body=>{setHours(body.hours);setExceptions(body.exceptions??[]);setMessage("")}).catch(()=>setMessage("営業時間を取得できませんでした"))},[]);
  function patchPeriod(prefix:"lunch"|"dinner",value:Period){setHours(current=>current?{...current,[`${prefix}Enabled`]:value.enabled,[`${prefix}Start`]:value.start,[`${prefix}LastOrder`]:value.lastOrder,[`${prefix}End`]:value.end,[`${prefix}Days`]:value.days}:current)}
  async function save(){if(!hours)return;setSaving(true);const response=await fetch("/api/v1/kitchen/business-hours",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(hours)});setMessage(response.ok?"営業時間を保存しました。モバイルオーダーとセルフレジへ反映されます。":"保存できませんでした");setSaving(false)}
  const calendar=useMemo(()=>{const[y,m]=month.split("-").map(Number),first=new Date(y,m-1,1),last=new Date(y,m,0);return[...Array(first.getDay()).fill(null),...Array.from({length:last.getDate()},(_,index)=>`${month}-${String(index+1).padStart(2,"0")}`)] as (string|null)[]},[month]);
  const selected=exceptions.find(item=>item.date===date);
  return <section className="hours-workspace">
    <div className="workspace-head"><div><p>BUSINESS HOURS</p><h1>営業時間管理</h1><small>共通営業時間と、商品ジャンルごとの提供可能時間を編集します。</small></div></div>
    {hours&&<div className="hours-grid"><PeriodCard title="ランチ" value={{enabled:hours.lunchEnabled,start:hours.lunchStart,lastOrder:hours.lunchLastOrder,end:hours.lunchEnd,days:hours.lunchDays}} onChange={value=>patchPeriod("lunch",value)}/><PeriodCard title="ディナー" value={{enabled:hours.dinnerEnabled,start:hours.dinnerStart,lastOrder:hours.dinnerLastOrder,end:hours.dinnerEnd,days:hours.dinnerDays}} onChange={value=>patchPeriod("dinner",value)}/></div>}
    <div className="hours-save"><span>{message}</span><button disabled={!hours||saving} onClick={()=>void save()}>{saving?"保存中…":"基本営業時間を保存"}</button></div>
    <CategoryAvailabilityManager/>
    <section className="kitchen-calendar"><header><div><small>MONTHLY BUSINESS CALENDAR</small><h2>月別営業カレンダー</h2></div><input type="month" value={month} onChange={event=>{setMonth(event.target.value);setDate("")}}/></header><div className="calendar-legend"><span className="closed">定休日・臨時休業</span><span className="irregular">イレギュラー営業</span></div><div className="kitchen-calendar-week">{["日","月","火","水","木","金","土"].map(item=><span key={item}>{item}</span>)}</div><div className="kitchen-calendar-grid">{calendar.map((day,index)=>{if(!day)return <span key={index}/>;const exception=exceptions.find(item=>item.date===day),visual=calendarVisual(day,hours,exception);return <button key={day} className={`${date===day?"selected":""} ${visual.className}`} onClick={()=>setDate(day)}><b>{Number(day.slice(-2))}</b><small>{visual.label}</small></button>})}</div>{date&&hours&&<ExceptionEditor key={date} value={selected??{date,status:"DEFAULT",lunchEnabled:true,dinnerEnabled:false,lunchStart:hours.lunchStart,lunchEnd:hours.lunchEnd,dinnerStart:hours.dinnerStart,dinnerEnd:hours.dinnerEnd,continuousStart:hours.lunchStart,continuousEnd:hours.dinnerEnd,continuousLastOrder:hours.dinnerLastOrder,note:""}} onSaved={value=>{setExceptions(rows=>[...rows.filter(item=>item.date!==value.date),value]);setMessage(`${value.date}の営業設定を保存しました`)}}/>}</section>
  </section>
}

function CategoryAvailabilityManager(){
  const[categories,setCategories]=useState<CategoryAvailability[]>([]),[message,setMessage]=useState("ジャンル別設定を読み込んでいます…"),[saving,setSaving]=useState(false);
  useEffect(()=>{void fetch("/api/v1/kitchen/menu-availability",{cache:"no-store"}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error();setCategories(body.schedules??[]);setMessage("")}).catch(()=>setMessage("ジャンル別の提供時間を取得できませんでした"))},[]);
  function update(categoryName:string,change:Partial<CategoryAvailability>){setCategories(current=>current.map(item=>item.category===categoryName?{...item,...change}:item))}
  function toggleDay(categoryName:string,day:number){const item=categories.find(category=>category.category===categoryName);if(!item)return;update(categoryName,{days:item.days.includes(day)?item.days.filter(value=>value!==day):[...item.days,day].sort()})}
  function riceWeekdayOff(){update("food-don",{enabled:true,days:[6,7],startTime:"11:30",endTime:"21:30",note:"平日は炊飯しない運用"});setMessage("ご飯ものを月〜金は提供停止、土日の11:30〜21:30のみ提供に設定しました。保存すると反映されます。")}
  async function save(){setSaving(true);const response=await fetch("/api/v1/kitchen/menu-availability",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({schedules:categories})});setMessage(response.ok?"ジャンル別の提供曜日・時間を保存しました。モバイルオーダーとセルフレジへ反映されます。":"ジャンル別設定を保存できませんでした");setSaving(false)}
  return <section className="category-availability"><header><div><small>MENU AVAILABILITY</small><h2>ジャンル別の提供曜日・時間</h2><p>設定時間外の商品はモバイルオーダーとセルフレジから自動的に外れます。</p></div><button className="rice-weekday-off" onClick={riceWeekdayOff}>平日のご飯ものを停止</button></header>{message&&<p className="availability-message">{message}</p>}<div className="availability-list">{categories.map(item=><details key={item.category} open={item.category==="food-don"}><summary><b>{categoryLabels[item.category]??item.category}</b><span>{item.enabled?`${item.days.map(day=>labels.find(([number])=>number===day)?.[1]).join("・")} ${item.startTime}〜${item.endTime}`:"営業時間内は常時提供"}</span></summary><div className="availability-rule"><label className="availability-enable"><input type="checkbox" checked={item.enabled} onChange={event=>update(item.category,{enabled:event.target.checked})}/>曜日・時間を制限する</label><div className="availability-weekdays">{labels.map(([day,label])=><button disabled={!item.enabled} className={item.days.includes(day)?"active":""} key={day} onClick={()=>toggleDay(item.category,day)}>{label}</button>)}</div><div className="availability-time-row"><label>提供開始<input disabled={!item.enabled} type="time" value={item.startTime} onChange={event=>update(item.category,{startTime:event.target.value})}/></label><label>提供終了<input disabled={!item.enabled} type="time" value={item.endTime} onChange={event=>update(item.category,{endTime:event.target.value})}/></label></div><label className="availability-note">運用メモ<input value={item.note} onChange={event=>update(item.category,{note:event.target.value})} placeholder="例：平日は炊飯しない"/></label></div></details>)}</div><footer><span>店舗自体が休業の場合は、ジャンル設定に関係なく注文できません。</span><button disabled={!categories.length||saving} onClick={()=>void save()}>{saving?"保存中…":"ジャンル別設定を保存"}</button></footer></section>
}

const statusLabel=(status?:Exception["status"])=>status==="CLOSED"?"休業":status==="CONTINUOUS"?"通し":status==="EVENT"?"イベント":status==="CUSTOM"?"変更":"通常";
const calendarVisual=(date:string,hours:Hours|null,exception?:Exception)=>{if(exception?.status==="CLOSED")return{className:"closed",label:"臨時休業"};if(exception&&["CONTINUOUS","EVENT","CUSTOM"].includes(exception.status))return{className:"irregular",label:statusLabel(exception.status)};const day=new Date(`${date}T00:00:00`).getDay()||7,open=!!hours&&((hours.lunchEnabled&&hours.lunchDays.includes(day))||(hours.dinnerEnabled&&hours.dinnerDays.includes(day)));return open?{className:"",label:"通常"}:{className:"closed",label:"定休日"}};
function PeriodCard({title,value,onChange}:{title:string;value:Period;onChange:(value:Period)=>void}){const toggle=(day:number)=>onChange({...value,days:value.days.includes(day)?value.days.filter(item=>item!==day):[...value.days,day].sort()});return <article className="hours-card"><header><h2>{title}</h2><label><input type="checkbox" checked={value.enabled} onChange={event=>onChange({...value,enabled:event.target.checked})}/>営業する</label></header><div className="hours-times"><label>営業開始<input type="time" value={value.start} onChange={event=>onChange({...value,start:event.target.value})}/></label><label>ラストオーダー<input type="time" value={value.lastOrder} onChange={event=>onChange({...value,lastOrder:event.target.value})}/></label><label>営業終了<input type="time" value={value.end} onChange={event=>onChange({...value,end:event.target.value})}/></label></div><div className="hours-days">{labels.map(([day,label])=><button key={day} className={value.days.includes(day)?"active":""} onClick={()=>toggle(day)}>{label}</button>)}</div></article>}
function ExceptionEditor({value,onSaved}:{value:Exception;onSaved:(value:Exception)=>void}){const[draft,setDraft]=useState(value),[saving,setSaving]=useState(false);const save=async()=>{setSaving(true);const response=await fetch("/api/v1/kitchen/business-hours",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({...draft,kind:"EXCEPTION"})});setSaving(false);if(response.ok)onSaved(draft)};return <div className="kitchen-exception"><h3>{draft.date} の営業設定</h3><div className="exception-statuses">{[["DEFAULT","通常"],["CLOSED","臨時休業"],["CONTINUOUS","通し営業"],["CUSTOM","時間変更"],["EVENT","イベント営業"]].map(([key,label])=><button key={key} className={draft.status===key?"active":""} onClick={()=>setDraft({...draft,status:key as Exception["status"]})}>{label}</button>)}</div>{draft.status==="CONTINUOUS"?<div className="exception-times"><label>開始<input type="time" value={draft.continuousStart} onChange={event=>setDraft({...draft,continuousStart:event.target.value})}/></label><label>ラストオーダー<input type="time" value={draft.continuousLastOrder} onChange={event=>setDraft({...draft,continuousLastOrder:event.target.value})}/></label><label>終了<input type="time" value={draft.continuousEnd} onChange={event=>setDraft({...draft,continuousEnd:event.target.value})}/></label></div>:draft.status!=="CLOSED"&&draft.status!=="DEFAULT"&&<div className="exception-times"><label>ランチ開始<input type="time" value={draft.lunchStart} onChange={event=>setDraft({...draft,lunchStart:event.target.value})}/></label><label>ランチ終了<input type="time" value={draft.lunchEnd} onChange={event=>setDraft({...draft,lunchEnd:event.target.value})}/></label><label>ディナー開始<input type="time" value={draft.dinnerStart} onChange={event=>setDraft({...draft,dinnerStart:event.target.value})}/></label><label>ディナー終了<input type="time" value={draft.dinnerEnd} onChange={event=>setDraft({...draft,dinnerEnd:event.target.value})}/></label></div>}<label className="exception-note">備考<input value={draft.note} onChange={event=>setDraft({...draft,note:event.target.value})}/></label><button className="exception-save" disabled={saving} onClick={()=>void save()}>{saving?"保存中…":"この日の設定を保存"}</button></div>}
