"use client";

import { useEffect, useState } from "react";

type TaskEvent={id:string;title:string;calls:string[];equipment:string;expectedSeconds:number;action:"COMPLETE"|"UNDO";createdAt:number;intervalSeconds:number|null;durationSeconds:number|null;overrunSeconds:number|null;measurementSource:"START"|"INTERVAL"};
type Bottleneck={title:string;equipment:string;adjustmentKey:"FRYER"|"MICROWAVE"|"PREP"|"DRINK";sampleCount:number;directSamples:number;expectedSeconds:number;averageActualSeconds:number;averageOverrunSeconds:number;maxOverrunSeconds:number;suggestedMinutes:number;suggestedBufferMinutes:number;needsReview:boolean;confidence:"ENOUGH"|"LOW"};
type Adjustment={adjustmentKey:string;bufferMinutes:number;sourceTitle:string;updatedAt:number};
type Analytics={summary:{completed:number;measured:number;delayed:number;onTime:number};adjustments:Record<string,Adjustment>;bottlenecks:Bottleneck[];events:TaskEvent[]};

function duration(seconds:number|null){if(seconds===null)return"計測開始";const value=Math.abs(seconds),minutes=Math.floor(value/60),rest=value%60;return`${minutes?`${minutes}分`:""}${rest?`${rest}秒`:minutes?"":"0秒"}`}

export default function TaskAnalytics(){
  const [data,setData]=useState<Analytics|null>(null),[message,setMessage]=useState("工程実績を読み込んでいます…"),[applying,setApplying]=useState("");
  async function load(){try{const response=await fetch("/api/v1/kitchen/task-analytics",{cache:"no-store"}),body=await response.json();if(!response.ok)throw new Error(body.error??"取得できませんでした");setData(body);setMessage("")}catch{setMessage("工程実績を取得できませんでした")}}
  async function applySuggestion(item:Bottleneck){if(item.confidence!=="ENOUGH"||!item.needsReview)return;const label=item.adjustmentKey==="FRYER"?"フライヤー":item.adjustmentKey==="MICROWAVE"?"電子レンジ":item.adjustmentKey==="DRINK"?"ドリンク":"盛付・準備";if(!window.confirm(`${label}を使う注文の提供予定へ、安全余裕 ${item.suggestedBufferMinutes}分を加算します。反映しますか？`))return;setApplying(item.adjustmentKey);try{const response=await fetch("/api/v1/kitchen/timing-adjustments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({adjustmentKey:item.adjustmentKey,sourceTitle:item.title,bufferMinutes:item.suggestedBufferMinutes,sampleCount:item.directSamples})}),body=await response.json();if(!response.ok)throw new Error(body.error??"反映できませんでした");await load()}catch{setMessage("安全余裕を反映できませんでした")}finally{setApplying("")}}
  useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),15000);return()=>window.clearInterval(timer)},[]);
  const completed=data?.events.filter(event=>event.action==="COMPLETE")??[];
  return <section className="analytics-workspace"><div className="workspace-head"><div><p>KITCHEN PERFORMANCE</p><h1>本日の工程実績</h1><small>最短工程ナビの完了間隔から、時間のかかった工程を確認できます</small></div><button onClick={()=>void load()}>再読み込み</button></div>
    {data&&<div className="analytics-summary"><article><span>完了した工程</span><b>{data.summary.completed}</b></article><article><span>予定内</span><b>{data.summary.onTime}</b></article><article className={data.summary.delayed?"warning":""}><span>1分超過</span><b>{data.summary.delayed}</b></article></div>}
    {data&&data.bottlenecks.length>0&&<section className="bottleneck-board"><header><div><small>提供予定の改善候補</small><h2>時間がかかりやすい工程</h2></div><span>作業開始から完了までを自動集計</span></header><div>{data.bottlenecks.map(item=>{const applied=data.adjustments?.[item.adjustmentKey];return <article className={item.needsReview?"review":"stable"} key={`${item.equipment}-${item.title}`}><div><small>{item.equipment}・実績 {item.sampleCount}回（直接計測 {item.directSamples}回）</small><b>{item.title}</b></div><dl><div><dt>現在の目安</dt><dd>{duration(item.expectedSeconds)}</dd></div><div><dt>平均実績</dt><dd>{duration(item.averageActualSeconds)}</dd></div><div><dt>判定</dt><dd>{item.needsReview?`目安を +${duration(item.averageOverrunSeconds)}`:"予定内"}</dd></div></dl><footer><span className={item.confidence==="ENOUGH"?"enough":"low"}>{item.confidence==="ENOUGH"?"判断可能":"直接計測を蓄積中"}</span>{item.needsReview&&(applied?.bufferMinutes===item.suggestedBufferMinutes?<strong className="applied-buffer">見積りへ＋{item.suggestedBufferMinutes}分 反映済み</strong>:<button disabled={item.confidence!=="ENOUGH"||applying===item.adjustmentKey} onClick={()=>void applySuggestion(item)}>{applying===item.adjustmentKey?"反映中…":item.confidence==="ENOUGH"?`見積りへ＋${item.suggestedBufferMinutes}分を反映`:"直接計測3回で反映可能"}</button>)}</footer></article>})}</div></section>}
    {message?<p className="analytics-empty">{message}</p>:completed.length?<div className="analytics-list">{completed.map(event=>{const delayed=(event.overrunSeconds??0)>60,actual=event.durationSeconds??event.intervalSeconds;return <article key={event.id} className={delayed?"delayed":""}><time>{new Date(event.createdAt).toLocaleTimeString("ja-JP",{hour:"2-digit",minute:"2-digit",second:"2-digit"})}</time><div><small>{event.equipment}{event.calls.length?`・${event.calls.join(" / ")}`:""}</small><b>{event.title}</b></div><div className="analytics-time"><span>{event.measurementSource==="START"?"作業開始から":"前工程から（参考）"} {duration(actual)}</span>{event.overrunSeconds!==null&&<strong className={delayed?"late":"ontime"}>{event.overrunSeconds>60?`目安より +${duration(event.overrunSeconds)}`:"予定内"}</strong>}</div></article>})}</div>:<p className="analytics-empty">本日完了した工程はまだありません</p>}
    <p className="analytics-note">※最短工程ナビの「いまやる作業」に表示された時刻から完了までを直接計測します。直接計測がない過去データのみ、前工程からの間隔を参考値として表示します。直接計測3回以上の候補だけ、確認後に安全余裕として反映できます。</p>
  </section>;
}
